server:
  port: 8201

spring:
  application:
    name: service-hosp
  profiles:
    active: dev
#----------------数据源配置----------------#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.93.223:3306/yygh_hosp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#  data:
#    mongodb:
#      host:
#      port:
#      database:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  cloud:
#    nacos:
#      discovery:
#        server-addr:
#    sentinel:
#      transport:
#        dashboard:
#
#  rabbitmq:
#    host:
#    port:
#    username:
#    password:

mybatis-plus:
  mapper-locations: mapper/xml/*.xml